/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/computer_desk/scene.gltf -r public
Author: Glowbox 3D (https://sketchfab.com/ra3id)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-desk-c67f61fa444044bcb88ec3e28f0ca7ac
Title: Computer Desk
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Computer(props) {
  const { nodes, materials } = useGLTF("/computer_desk/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube029_Material_0.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={20}
      />
    </group>
  );
}

useGLTF.preload("/computer_desk/scene.gltf");
